### PR TITLE
[ Issues #47 and #48 ] Updated master branch to latest 3.0 and ignored build files that are not necessary

### PR DESCRIPTION
**Pull request by jchavezlavalle**
- Fixes: #47 and #48 

Please notice that `_build` folder still exists but it has only 1 single folder needed: `_build/html/static/js` which contains only additional js code which can be updated later for our site to add additional features.

For example our footer: 
image

Has been coded with -> `_build/html/static/js/footer.js`

### CODE REVIEW

**Comment by jchavezlavalle** [comment]
@GodloveD This is RFR, contains @WestleyK  's changes on Contributing section and missing .github files which have been merged from 3.0 branch

**Review by WestleyK — APPROVED** [review]
Looks good to me! Imo...

**Review by GodloveD — APPROVED** [review]
lgtm

**Comment by hall** [comment]
@devprincess, instead of modifying the build output directory, you can add a [method](https://docs.readthedocs.io/en/latest/guides/adding-custom-css.html) to `conf.py` that will include static content:
```py
def setup(app):
    app.add_stylesheet('custom.css')
    app.add_javascript('custom.js')
```
Then just add those files (`custom.css` and `custom.js`) under the [`html_static_path`](https://github.com/sylabs/singularity-userdocs/blob/master/conf.py#L145) and it should work as expected.

**Comment by GodloveD** [comment]
Oh that sounds like a great idea @hall!  What do you think @devprincess?

**Pull request merged**
