### PR TITLE
Update installation instructions -> no git dependency

### LINKED ISSUE #100: Update Install Docs to use WGET instead of Git like in RPM Install
## Which Document page:

On what page is the problem?
https://github.com/sylabs/singularity-userdocs/blob/master/installation.rst
https://github.com/sylabs/singularity/blob/master/INSTALL.md

### Expected results:

There would be specific instructions on how to install Singularity after downloading the `.tar.gz` files from the GitHub Releases page: https://github.com/sylabs/singularity/releases

### Actual results:

A user had issues installing the releases by downloading the `.tar.gz` files most likely from the GitHub releases page: https://github.com/sylabs/singularity/releases

The install instructions do not have specific instructions for how to use use this `.tar.gz` except for the RPM Build instructions.

The instructions for non-RPM is to use `git clone` or `go get` and to make sure it is in the `$GOPATH` directory of `$GOPATH/src/github.com/sylabs/singularity`

Technically just like for the RPM Build, `git` is not a requirement to install Singularity, and even if it is (`go get` and `dep` requires git afaik), it would be clearer if there we're instructions that did not require knowledge of using git to install singularity.

Something like
```sh
export VERSION=3.0.1 && # adjust this as necessary \
    mkdir -p $GOPATH/src/github.com/sylabs && \
    cd $GOPATH/src/github.com/sylabs && \
    wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz && \
    tar -xzf singularity-${VERSION}.tar.gz && \
    cd ./singularity && \
    ./mconfig
```

### PR DESCRIPTION
**Pull request by jchavezlavalle**
## Description of the Pull Request (PR):

Update installation instructions, no need to install git for installing Singularity.

## This fixes or addresses the following GitHub issues:

- Fixes #100 :100: ha!

### CODE REVIEW

**Comment by jchavezlavalle** [comment]
Heya @kzap could you review if this fixes #100 ? thank you!

**Review by kzap — APPROVED** [review]
looks good but does it show up properly when the docs are compiled, github preview of it does not show the code block :)

https://github.com/sylabs/singularity-userdocs/blob/a9f242cbf13b5013a5d6f7f3a3c9a2e35cafa228/installation.rst

**Comment by jchavezlavalle** [comment]
there was a formatting issue, thanks for noticing @kzap, could you review now? thank you!

**Review by kzap — APPROVED** [review]
looks good 👍

**Pull request merged**
